name: Validate build

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/validate-build.yml"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install --no-audit --no-fund
      - run: npm run build
